name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 7.4
          - php: 8.0
          - php: 8.1
          - php: 8.2
          - php: 8.3
          - php: 8.4

    name: 'PHP ${{ matrix.php }}'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '${{ matrix.php }}'

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --ansi --prefer-dist --no-interaction --no-scripts

      - name: PHPUnit
        run: vendor/bin/phpunit --colors=always
